global:
  replicaCount: 1
  revisionHistoryLimit: 3

  image:
    repository: yah561899/sampleapi
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: LoadBalancer
    port: 8083
    targetPort: 8082

  resources:
    requests:
      cpu: "20m"
      memory: "55M"

  livenessProbe:
    path: /api/HealthCheck/readiness
    port: 8082
    initialDelaySeconds: 90
    timeoutSeconds: 10

  readinessProbe:
    path: /api/HealthCheck/readiness
    port: 8082
    initialDelaySeconds: 30
    timeoutSeconds: 10
    periodSeconds: 10

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1